FROM flink:1.18

USER root

RUN pip install --no-cache-dir \
    apache-flink==1.18.0 \
    kafka-python==2.0.2 \
    boto3==1.34.0 \
    pandas==2.2.0

COPY flink/ /opt/flink-jobs/
COPY configs/flink/flink-conf.yaml /opt/flink/conf/flink-conf.yaml

ENV PYTHONPATH="/opt/flink-jobs:${PYTHONPATH}"

USER flink
