replicaCount: 3

image:
  repository: ml-app
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: LoadBalancer
  port: 80
  targetPort: 8000

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70

env:
  mlflowTrackingUri: "http://mlflow-service:5000"

mlflow:
  enabled: true
  image:
    repository: ghcr.io/mlflow/mlflow
    tag: v2.10.2
  persistence:
    size: 10Gi
